#! /bin/bash
for i in intro chap1 chap2 nongauss splines assessment pipelines trees kernels; do
    for j in pdf html; do ## html docx pdf slides.html
    	make docs/notes/$i.$j
    done
    ## mv notes/$i.slides.html docs/notes  ## hack
done
